spring:
  # 数据库连接池的配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/health?useSSL=false
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
    max-file-size: 10MB
    max-request-size: 50MB

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wenguodong.health.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  port: 80

